language: python
python:
  - "2.7"
  - "3.6"

matrix:
  include:
  - name: "3.5 Unit Test"
    python: "3.5"
    env: TEST_SUITE=suite_3_5_unit
    
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python testpy.py $TEST_SUITE
